language: node_js
node_js:
- '4'
branches:
  only:
  - master
before_install:
- openssl aes-256-cbc -K $encrypted_b32aa25639e7_key -iv $encrypted_b32aa25639e7_iv
  -in ./.travis/id_rsa.enc -out ~/.ssh/id_rsa -d
- cp .travis/ssh_config ~/.ssh/config
- chmod 600 ~/.ssh/id_rsa
- eval $(ssh-agent)
- ssh-add ~/.ssh/id_rsa
- git config --global user.name '31501364'
- git config --global user.email 357216043@qq.com
install:
- npm install -g hexo-cli --save
- npm install -g yuque-hexo --save
- npm install
script:
- npm run deploy
# cache:
#   directories:
#   - node_modules
